language: node_js

node_js: "8"

addons:
    code_climate:
        repo_token: f0411ee6db8484048836d3b2ccff1207ca78e8da422549c0256bc6a3c6e53634

sudo: required
services: postgresql

install: yarn

before_script: yarn start & sleep 5
script: yarn test